In [1]:
import numpy as np

In [4]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
np.random.seed(280400)

x = np.random.uniform(size=(3,2))
print(x)

[[0.45471242 0.73928005]
 [0.06363616 0.48752939]
 [0.00669546 0.59274984]]


In [17]:
x[0]

array([0.45471242, 0.73928005])

In [18]:
x[0:1:, ::]

array([[0.45471242, 0.73928005]])

In [19]:
x[-1]

array([0.00669546, 0.59274984])

In [20]:
x[-2:]

array([[0.06363616, 0.48752939],
       [0.00669546, 0.59274984]])

In [25]:
x[:, -1]

array([0.73928005, 0.48752939, 0.59274984])

In [33]:
x[0::2, :]

array([[0.45471242, 0.73928005],
       [0.00669546, 0.59274984]])

In [46]:
x.flatten()

array([0.45471242, 0.73928005, 0.06363616, 0.48752939, 0.00669546,
       0.59274984])

In [47]:
x.T

array([[0.45471242, 0.06363616, 0.00669546],
       [0.73928005, 0.48752939, 0.59274984]])